server:
  port: 8082

spring:
  application:
    name : activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/v2/