spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnessyoga_user_db
    username: postgres
    password: Admin@2026
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

